{% set name = "npmignore" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/npmignore/-/npmignore-{{ version }}.tgz
  sha256: 23974a4b78bb822a67698d18bf208f41dbb610592b53ed6f720b1529841a968f

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - npmignore --help

about:
  home: https://github.com/ljharb/npmignore
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: 'Command line tool for creating or updating a .npmignore file based on .gitignore'

extra:
  recipe-maintainers:
    - danielnachun
    - xhochy
