{% set name = "npmignore" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ljharb/npmignore/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 33922f1f0b6eaeb5aedffd2f460c4601da389da357dc1ae4d260b5e7c68c1c50

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - npmignore --help

about:
  home: https://github.com/ljharb/npmignore
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: 'Command line tool for creating or updating a .npmignore file based on .gitignore'

extra:
  recipe-maintainers:
    - xhochy
