schema_version: 1

context:
  version: "0.3.4"

package:
  name: npmignore
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/npmignore/-/npmignore-${{ version }}.tgz
  sha256: e8d68c679bb9b09376b2ee2bb48a6b2edc0852b38306c07b31a8500885d5b5d5

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - npmignore --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Command line tool for creating or updating a .npmignore file based on .gitignore
  homepage: https://github.com/ljharb/npmignore

extra:
  recipe-maintainers:
    - danielnachun
    - xhochy
